Repository openfun/marsha, pull requests merged in 2018-11, with the labels that each got.

#125 🐛(terraform) change expected file name in lambda terraform file
  src/aws/lambda.tf
Labels: bug, needs review

#136 ♻️ (front) use an Enum for app state name
  src/frontend/components/RedirectOnLoad/RedirectOnLoad.spec.tsx
  src/frontend/components/RedirectOnLoad/RedirectOnLoad.tsx
  src/frontend/types/AppData.ts
Labels: improvement, needs review

#140 Fix an issue with VideoPlayer when the video is first ready
  src/frontend/components/AppRoutes/AppRoutes.tsx
  src/frontend/components/Dashboard/Dashboard.spec.tsx
  src/frontend/components/Dashboard/Dashboard.tsx
Labels: bug

#148 ⚡(front) add helper in yarn script to run easily linters
  .circleci/config.yml
  src/frontend/package.json
Labels: improvement

#156 🐛(videos) fix a 500 error when serializing videos
  src/backend/marsha/core/serializers.py
  src/backend/marsha/core/tests/test_views_lti_video.py
Labels: bug

#153 Fix the update-state request serializer
  src/backend/marsha/core/serializers.py
  src/backend/marsha/core/tests/test_serializers_upload_confirm.py
Labels: bug

#144 Add origin checks to lti video
  src/backend/marsha/core/lti.py
  src/backend/marsha/core/tests/test_lti.py
Labels: improvement, work in progress
