Repository openfun/marsha, pull requests merged in 2019-02, with the labels that each got.

#227 🐛(timedtext) add vtt extensions to destination files
  src/aws/lambda-encode/src/encodeTimedTextTrack.js
  src/aws/lambda-encode/src/encodeTimedTextTrack.spec.js
Labels: bug

#230 ⚡️(logging) add the release to Sentry events
  src/backend/marsha/settings.py
Labels: improvement, work in progress

#235 ♻️(timedtext) load timed text tracks from object video if present
  src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx
  src/frontend/components/VideoPlayer/VideoPlayer.tsx
  src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.tsx
  src/frontend/data/bootstrapStore.ts
  src/frontend/types/tracks.ts
Labels: improvement, needs review

#237 ✨(timedtexttrack) update track when its state changes once uploaded
  src/frontend/components/TimedTextListItem/TimedTextListItem.spec.tsx
  src/frontend/components/TimedTextListItem/TimedTextListItem.tsx
  src/frontend/components/TimedTextListItemConnected/TimedTextListItemConnected.ts
Labels: improvement

#242 ⚡️(player) use a poster to speed up player displaying
  src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx
  src/frontend/components/VideoPlayer/VideoPlayer.tsx
Labels: improvement, needs review

#243 🐛(timedtexttrack) exclude existing language in language choices
  src/frontend/components/DashboardTimedTextManager/DashboardTimedTextManager.tsx
  src/frontend/components/TimedTextCreationForm/TimedTextCreationForm.spec.tsx
  src/frontend/components/TimedTextCreationForm/TimedTextCreationForm.tsx
Labels: bug, improvement

#244 ✨(player) display language label in Plyr captions
  src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx
  src/frontend/components/VideoPlayer/VideoPlayer.tsx
  src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.spec.tsx
  src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.tsx
Labels: improvement

#234 🐛(api) allow student to access metadata timedtexttrack's action
  src/backend/marsha/core/api.py
  src/backend/marsha/core/tests/test_api_timed_text_track.py
Labels: improvement, needs review
