Repository openfun/marsha, pull requests merged in 2019-09, with the labels that each got.

#503 🌐(i18n) update translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/translations/es_ES.po
  src/frontend/translations/fr_CA.po
  src/frontend/translations/fr_FR.po
Labels: FUN Team

#512 ✨(gunicorn) configure worker and threads
  CHANGELOG.md
  docker/files/usr/local/etc/gunicorn/marsha.py
Labels: improvement

#514 ✨(gunicorn) configure worker and threads
  CHANGELOG.md
  docker/files/usr/local/etc/gunicorn/marsha.py
Labels: FUN Team

#513 ⬆️(dependencies) update @openfun/substr in lambda-encode
  CHANGELOG.md
  src/aws/lambda-encode/package.json
  src/aws/lambda-encode/yarn.lock
Labels: FUN Team

#516 🔖(patch) release version 2.10.2
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#520 🔥(permissions) remove outdated video_id parameter from JWT token
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/views.py
  src/frontend/types/jwt.ts
Labels: improvement

#518 ♻️(permissions) group all permissions in the JWT token
  CHANGELOG.md
  src/backend/marsha/core/lti/__init__.py
  src/backend/marsha/core/permissions.py
  src/backend/marsha/core/tests/test_api_document.py
  src/backend/marsha/core/tests/test_api_thumbnail.py
  src/backend/marsha/core/tests/test_api_timed_text_track.py
  src/backend/marsha/core/tests/test_api_video.py
  src/backend/marsha/core/tests/test_views_lti_document.py
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/views.py
Labels: improvement

#522 ♻️(lti) refactor consumer site domain check in bypass requests
  src/backend/marsha/core/lti/__init__.py
  src/backend/marsha/core/tests/test_views_lti_video.py
Labels: improvement

#523 ⬆️ (circle) upgrade crowdin image version
  .circleci/config.yml
  CHANGELOG.md
Labels: FUN Team, improvement

#524 ⚡️(lti) cache database queries and serialization in LTI views
  CHANGELOG.md
  src/backend/marsha/core/lti/__init__.py
  src/backend/marsha/core/lti/utils.py
  src/backend/marsha/core/tests/test_lti.py
  src/backend/marsha/core/tests/test_lti_utils.py
  src/backend/marsha/core/tests/test_views_lti_cache.py
  src/backend/marsha/core/tests/test_views_lti_document.py
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/views.py
  src/backend/marsha/settings.py
Labels: improvement

#528 ♻️(project) rename test methods and view class as per handbook guideline
  src/backend/marsha/core/tests/test_views_lti_development.py
  src/backend/marsha/core/tests/test_views_lti_document.py
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/views.py
  src/backend/marsha/urls.py
Labels: improvement

#527 ♻️(configuration) remove redundant setting STATICFILES_AWS_ENABLED
  CHANGELOG.md
  src/backend/marsha/core/templates/core/lti.html
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/views.py
  src/backend/marsha/settings.py
  src/frontend/public-path.js
Labels: improvement

#531 🐳(python) upgrade to python 3.7
  CHANGELOG.md
  Dockerfile
Labels: improvement

#529 ♻️(front) group all permissions in the JWT token
  src/frontend/components/InstructorView/index.spec.tsx
  src/frontend/components/InstructorView/index.tsx
  src/frontend/components/InstructorWrapper/index.spec.tsx
  src/frontend/components/InstructorWrapper/index.tsx
  src/frontend/components/RedirectOnLoad/index.spec.tsx
  src/frontend/components/RedirectOnLoad/index.tsx
  src/frontend/types/AppData.ts
  src/frontend/types/jwt.ts
Labels: improvement

#517 ♻️(front) create a dedicated component to manage document title form
  src/frontend/components/DashboardDocument/index.spec.tsx
  src/frontend/components/DashboardDocument/index.tsx
  src/frontend/components/DashboardDocumentTitleForm/index.spec.tsx
  src/frontend/components/DashboardDocumentTitleForm/index.tsx
Labels: bug

#533 🌐(i18n) update translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/translations/es_ES.po
  src/frontend/translations/fr_CA.po
  src/frontend/translations/fr_FR.po
Labels: FUN Team

#535 ♻️(statics) change how static base url is computed
  src/backend/marsha/core/views.py
  src/frontend/public-path.js
Labels: bug

#538 ✨(back) introduce a new setting ABSOLUTE_STATIC_URL
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/views.py
  src/backend/marsha/settings.py
Labels: bug, improvement

#539 🔧(circleci) migrate image to python 3.7
  .circleci/config.yml
Labels: improvement

#541 🐛(front) fix bad usage of permissions.can_access_dashboard from JWT
  src/frontend/components/InstructorView/index.spec.tsx
  src/frontend/components/InstructorView/index.tsx
Labels: bug, critical

#545 📝(readme) add a link to the wikipedia page for LTI
  README.md
Labels: easy pick, improvement
