Repository openfun/marsha, pull requests merged in 2019-03, with the labels that each got.

#251 📌(AWS) force merge version to at least version 1.2.1
  src/aws/lambda-configure/package.json
  src/aws/lambda-configure/yarn.lock
  src/aws/lambda-encode/package.json
  src/aws/lambda-encode/yarn.lock
  src/aws/lambda-update-state/package.json
  src/aws/lambda-update-state/yarn.lock
Labels: improvement

#254 🔖(chore) bump release to 2.3.1
  CHANGELOG.md
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN

#257 Add a feature check for MSE support before using DashJS in the player
  src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx
  src/frontend/components/VideoPlayer/VideoPlayer.tsx
  src/frontend/utils/isAbrSupported.ts
Labels: bug, critical

#264 🐛(crowdin) use fundocker image to run crowdin-cli
  docker-compose.yml
Labels: bug, improvement, needs review

#266 🐛(crowdin) use fundocker/crowdin image in CI docker-compose
  docker/compose/ci/docker-compose.yml
Labels: bug

#270 🐛(docker) change frontend build to fix translations
  Dockerfile
Labels: bug, needs review

#269 🔖(chore) bump release to 2.5.0
  CHANGELOG.md
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN

#272 🔧(front) use core-js 3 combined with babel-preset-env
  src/frontend/babel.config.js
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: improvement, needs review
