Repository openfun/marsha, pull requests merged in 2019-01, with the labels that each got.

#173 ✅(VideoPlayer) correctly test shaka player instantiation
  src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx
Labels: bug, needs review

#184 Isolate route definitions to avoid circular dependencies
  src/frontend/components/AppRoutes/AppRoutes.tsx
  src/frontend/components/Dashboard/Dashboard.tsx
  src/frontend/components/Dashboard/route.ts
  src/frontend/components/DashboardVideoPane/DashboardVideoPane.tsx
  src/frontend/components/DashboardVideoPaneButtons/DashboardVideoPaneButtons.tsx
  src/frontend/components/ErrorComponent/ErrorComponent.tsx
  src/frontend/components/ErrorComponent/route.ts
  src/frontend/components/InstructorView/InstructorView.spec.tsx
  src/frontend/components/InstructorView/InstructorView.tsx
  src/frontend/components/RedirectOnLoad/RedirectOnLoad.spec.tsx
  src/frontend/components/RedirectOnLoad/RedirectOnLoad.tsx
  src/frontend/components/RedirectOnLoad/route.ts
  src/frontend/components/UploadForm/UploadForm.spec.tsx
  src/frontend/components/UploadForm/UploadForm.tsx
  src/frontend/components/UploadForm/route.ts
  src/frontend/components/VideoPlayer/VideoPlayer.tsx
  src/frontend/components/VideoPlayer/route.ts
Labels: improvement, needs review

#189 Auto portability between consumer sites
  CHANGELOG.md
  src/backend/marsha/core/lti.py
  src/backend/marsha/core/migrations/0006_auto_20190114_1650.py
  src/backend/marsha/core/models/account.py
  src/backend/marsha/core/tests/test_lti.py
Labels: feature

#192 🐛(video) fix initiate upload updating all objects instead of just one
  src/backend/marsha/core/api.py
  src/backend/marsha/core/tests/test_api_timed_text_track.py
  src/backend/marsha/core/tests/test_api_video.py
Labels: bug, critical, needs review
