Repository openfun/marsha, pull requests merged in 2019-10, with the labels that each got.

#555 ✨(AWS) upgrade lambdas to use node 10
  .circleci/config.yml
  CHANGELOG.md
  src/aws/Makefile
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda.tf
  src/aws/state.tf
Labels: improvement

#560 🔖(minor) bump release to 3.1.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#564 🔖(patch) bump release to 3.1.1
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#569 🐛(back) ignore domain check if http referer is missing
  CHANGELOG.md
  src/backend/marsha/core/lti/__init__.py
  src/backend/marsha/core/tests/test_lti.py
Labels: bug

#568 🏁(frontent) polyfill CustomEvents for IE11
  src/frontend/index.tsx
  src/frontend/package.json
  src/frontend/types/libs/custom-event-polyfill/index.d.ts
  src/frontend/yarn.lock
Labels: bug, dependencies

#566 🐛(front) use plyr instance directly in event listeners
  src/frontend/Player/createPlyrPlayer.ts
Labels: bug

#571 🐛(front) test if Intl exists using global object
  CHANGELOG.md
  src/frontend/index.tsx
Labels: bug

#574 📝(Readme) add information about testing front application
  README.md
Labels: FUN Team

#577 🔖(patch) bump release to 3.1.3
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#581 🔖(patch) bump release to 3.1.4
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#579 🐛(AWS) encode only transcripts and simply convert others
  CHANGELOG.md
  src/aws/lambda-encode/index.js
  src/aws/lambda-encode/index.spec.js
  src/aws/lambda-encode/src/encodeTimedTextTrack.js
  src/aws/lambda-encode/src/encodeTimedTextTrack.spec.js
Labels: bug, needs review

#582 📝(README) add information about document management
  README.md
Labels: improvement

#585 🔖(patch) bump release to 3.1.4
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#586 ♻️(recycle) remove dockerize in dev image
  .circleci/config.yml
  Makefile
  docker-compose.yml
  docker/images/dev/Dockerfile
Labels: improvement

#587 ♻️(backend) move defaults settings to settings file
  CHANGELOG.md
  src/backend/marsha/core/api.py
  src/backend/marsha/core/defaults.py
  src/backend/marsha/core/utils/s3_utils.py
  src/backend/marsha/settings.py
Labels: improvement

#588 🔖(patch) bump release to 3.1.6
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#595 🐛(front) choose video quality when ABR is not available
  CHANGELOG.md
  src/frontend/Player/createPlyrPlayer.spec.ts
  src/frontend/Player/createPlyrPlayer.ts
  src/frontend/utils/isAbrSupported.ts
Labels: bug, critical, needs review

#596 🐛(xapi) initliaze xapi module only when all video data are available
  CHANGELOG.md
  src/frontend/Player/createPlyrPlayer.spec.ts
  src/frontend/Player/createPlyrPlayer.ts
  src/frontend/XAPI/XAPIStatement.spec.ts
  src/frontend/XAPI/XAPIStatement.ts
Labels: bug, needs review
