Repository openfun/marsha, pull requests merged in 2019-08, with the labels that each got.

#470 🐛(frontend) fix an issue with video polling
  CHANGELOG.md
  src/frontend/data/sideEffects/upload/index.ts
Labels: bug

#476 ♻️(front) shorten plyr seek time
  CHANGELOG.md
  src/frontend/Player/createPlyrPlayer.ts
Labels: improvement

#474 ♻️(front) change message in <InstructorView /> when a video is read only
  src/frontend/__mocks__/react-intl.tsx
  src/frontend/components/InstructorView/index.spec.tsx
  src/frontend/components/InstructorView/index.tsx
Labels: improvement, needs review

#477 ✨(front) seek to the cue's start time when a user click on it
  CHANGELOG.md
  src/frontend/Player/createPlyrPlayer.ts
  src/frontend/components/TranscriptSentence/index.spec.tsx
  src/frontend/components/TranscriptSentence/index.tsx
  src/frontend/data/stores/useTranscriptTimeSelector/index.tsx
Labels: improvement, needs review

#480 🔖(minor) bump release to 2.10.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN

#482 🐛(front) ensure useThumbnail return null when there is no thumbnail
  CHANGELOG.md
  src/frontend/data/stores/useThumbnail/index.spec.tsx
  src/frontend/data/stores/useThumbnail/index.tsx
Labels: bug

#483 🐛(front) remove undefined values in stores when removing resource
  CHANGELOG.md
  src/frontend/data/stores/actions.ts
  src/frontend/data/stores/useTimedTextTrack/index.spec.tsx
Labels: bug, needs review

#484 🔖(patch) bump release to 2.10.1
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN

#491 🔥(back) remove deprecated settings
  CHANGELOG.md
  docs/env.md
  env.d/development.dist
  src/backend/marsha/core/api.py
  src/backend/marsha/core/tests/test_api_xapi_statement.py
  src/backend/marsha/settings.py
Labels: FUN

#492 ♻️(resources) share same resource name between front and back
  CHANGELOG.md
  src/backend/marsha/core/models/file.py
  src/backend/marsha/core/models/video.py
  src/backend/marsha/core/tests/test_api_thumbnail.py
  src/backend/marsha/core/views.py
  src/backend/marsha/urls.py
  src/frontend/components/DashboardThumbnail/index.spec.tsx
  src/frontend/components/DashboardThumbnail/index.tsx
  src/frontend/components/UploadForm/index.tsx
  src/frontend/data/sideEffects/createThumbnail/index.spec.ts
  src/frontend/data/sideEffects/createThumbnail/index.ts
  src/frontend/data/sideEffects/upload/index.spec.ts
  src/frontend/data/sideEffects/upload/index.ts
  src/frontend/data/stores/actions.spec.ts
  src/frontend/data/stores/generics.spec.ts
  src/frontend/data/stores/generics.ts
  src/frontend/data/stores/useThumbnail/index.spec.tsx
  src/frontend/data/stores/useThumbnail/index.tsx
  src/frontend/types/models.ts
  src/frontend/types/stores.ts
Labels: improvement

#499 ♻️ (model) rename is_ready_* properties in is_ready_to_show
  CHANGELOG.md
  src/backend/marsha/core/models/base.py
  src/backend/marsha/core/models/file.py
  src/backend/marsha/core/models/video.py
  src/backend/marsha/core/serializers.py
  src/backend/marsha/core/tests/test_api_document.py
  src/backend/marsha/core/tests/test_api_thumbnail.py
  src/backend/marsha/core/tests/test_api_timed_text_track.py
  src/backend/marsha/core/tests/test_api_video.py
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/frontend/components/DashboardDocument/index.spec.tsx
  src/frontend/components/DashboardThumbnail/index.spec.tsx
  src/frontend/components/DashboardThumbnail/index.tsx
  src/frontend/components/DashboardThumbnailDisplay/index.spec.tsx
  src/frontend/components/DashboardThumbnailDisplay/index.tsx
  src/frontend/components/DashboardTimedTextPane/index.spec.tsx
  src/frontend/components/DashboardVideoPane/index.spec.tsx
  src/frontend/components/DashboardVideoPane/index.tsx
  src/frontend/components/DashboardVideoPaneDownloadOption/index.spec.tsx
  src/frontend/components/DocumentPlayer/index.spec.tsx
  src/frontend/components/DownloadVideo/index.spec.tsx
  src/frontend/components/RedirectOnLoad/index.spec.tsx
  src/frontend/components/RedirectOnLoad/index.tsx
  src/frontend/components/TimedTextCreationForm/index.spec.tsx
  src/frontend/components/TimedTextListItem/index.spec.tsx
  src/frontend/components/TimedTextListItem/index.tsx
  src/frontend/components/TranscriptReader/index.spec.tsx
  src/frontend/components/Transcripts/index.spec.tsx
  src/frontend/components/UploadForm/index.spec.tsx
  src/frontend/components/VideoPlayer/index.spec.tsx
  src/frontend/components/VideoPlayer/index.tsx
  src/frontend/components/VideoPlayer/indexWithDashjs.spec.tsx
  src/frontend/data/sideEffects/getResourceList/index.spec.tsx
  src/frontend/data/sideEffects/pollForTrack/index.spec.tsx
  src/frontend/data/sideEffects/pollForTrack/index.tsx
  src/frontend/data/sideEffects/updateResource/index.spec.ts
  src/frontend/data/sideEffects/upload/index.spec.ts
  src/frontend/data/stores/useThumbnail/index.spec.tsx
  src/frontend/data/stores/useTimedTextTrack/index.spec.tsx
  src/frontend/data/stores/useVideo/index.spec.tsx
  src/frontend/types/file.ts
  src/frontend/types/tracks.ts
Labels: improvement

#500 ♻️(front) create only one route to manage all players
  src/frontend/components/AppRoutes/index.tsx
  src/frontend/components/DashboardDocument/index.tsx
  src/frontend/components/DashboardPaneButtons/index.spec.tsx
  src/frontend/components/DashboardPaneButtons/index.tsx
  src/frontend/components/DashboardVideoPane/index.tsx
  src/frontend/components/DocumentPlayer/route.ts
  src/frontend/components/RedirectOnLoad/index.spec.tsx
  src/frontend/components/RedirectOnLoad/index.tsx
  src/frontend/components/VideoPlayer/route.ts
  src/frontend/components/routes.ts
  src/frontend/types/AppData.ts
Labels: improvement

#501 🌐(front) update some descriptions in plyr translation
  src/frontend/Player/i18n/plyrTranslation.ts
Labels: easy pick
