Repository openfun/marsha, pull requests merged in 2019-06, with the labels that each got.

#404 🐛(backend) use secure cookie only in production
  CHANGELOG.md
  src/backend/marsha/settings.py
Labels: bug

#411 🔖(patch) bump release to 2.8.3
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN

#412 🐛(xAPI) be sure to send completed event when progress has reached 100%
  CHANGELOG.md
  src/frontend/XAPI/XAPIStatement.spec.ts
  src/frontend/XAPI/XAPIStatement.ts
Labels: bug, needs review

#415 🔖(patch) bump release to 2.8.4
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN

#416 compute xapi completion threshold
  CHANGELOG.md
  src/frontend/Player/createPlyrPlayer.ts
  src/frontend/XAPI/XAPIStatement.spec.ts
  src/frontend/XAPI/XAPIStatement.ts
  src/frontend/types/XAPI.ts
Labels: improvement, needs review

#419 ✨(xAPI) send terminated statement when use leave the page
  CHANGELOG.md
  src/frontend/Player/createPlyrPlayer.ts
  src/frontend/XAPI/XAPIStatement.spec.ts
  src/frontend/XAPI/XAPIStatement.ts
Labels: improvement, needs review

#420 ✨(xAPI) prevent to lose an upload when a page is leaved
  CHANGELOG.md
  src/frontend/components/UploadForm/UploadForm.spec.tsx
  src/frontend/components/UploadForm/UploadForm.tsx
Labels: feature request, improvement

#421 🔖(minor) bump release to 2.9.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN

#424 🐛(xAPI) add time in interacted xapi payload
  CHANGELOG.md
  src/frontend/Player/createPlyrPlayer.ts
  src/frontend/XAPI/XAPIStatement.spec.ts
  src/frontend/XAPI/XAPIStatement.ts
  src/frontend/types/XAPI.ts
Labels: bug, improvement, needs review

#425 ♻️(front) hide dashboard button when a video is in read only
  CHANGELOG.md
  src/frontend/components/InstructorView/InstructorView.spec.tsx
  src/frontend/components/InstructorView/InstructorView.tsx
Labels: improvement

#426 📌(AWS) pin terraform to version 0.11.14
  CHANGELOG.md
  src/aws/bin/state
  src/aws/bin/terraform
Labels: improvement, needs review

#423 🚸(video) add the `show_download` flag to the video admin view
  CHANGELOG.md
  src/backend/marsha/core/admin.py
Labels: improvement

#427 🚧(front) reactivate HLS support
  CHANGELOG.md
  src/frontend/components/VideoPlayer/index.spec.tsx
  src/frontend/components/VideoPlayer/index.tsx
  src/frontend/utils/isAbrSupported.ts
Labels: improvement, needs review

#433 ♻️(front) refactor UploadForm component
  src/frontend/components/AppRoutes/index.tsx
  src/frontend/components/UploadForm/UploadForm.spec.tsx
  src/frontend/components/UploadForm/UploadForm.tsx
  src/frontend/components/UploadForm/index.spec.tsx
  src/frontend/components/UploadForm/index.tsx
  src/frontend/components/UploadFormConnected/UploadFormConnected.spec.tsx
  src/frontend/components/UploadFormConnected/UploadFormConnected.tsx
  src/frontend/data/sideEffects/upload/index.spec.ts
  src/frontend/data/sideEffects/upload/index.ts
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: improvement

#439 ♻️(front) refactor RedirectOnLoad component
  src/frontend/components/AppRoutes/index.tsx
  src/frontend/components/RedirectOnLoad/RedirectOnLoad.spec.tsx
  src/frontend/components/RedirectOnLoad/index.spec.tsx
  src/frontend/components/RedirectOnLoad/index.tsx
  src/frontend/components/RedirectOnLoadConnected/RedirectOnLoadConnected.tsx
Labels: improvement, needs review

#436 Refactor <DashboardVideoPaneDownloadOption />
  src/frontend/components/DashboardVideoPane/index.tsx
  src/frontend/components/DashboardVideoPaneDownloadOption/DashboardVideoPaneDownloadOption.spec.tsx
  src/frontend/components/DashboardVideoPaneDownloadOption/index.spec.tsx
  src/frontend/components/DashboardVideoPaneDownloadOption/index.tsx
  src/frontend/components/DashboardVideoPaneDownloadOptionConnected/DashboardVideoPaneDownloadOptionConnected.tsx
Labels: improvement
