Repository openfun/marsha, pull requests merged in 2020-01, with the labels that each got.

#622 ✅ Add tests for the get_release method in settings
  src/backend/marsha/core/tests/test_settings.py
  src/backend/marsha/settings.py
Labels: improvement, needs review

#627 🐳(build) enhance .dockerignore file
  .dockerignore
Labels: improvement

#628 🐛(statics) ignore only js statics in .dockerignore
  .dockerignore
Labels: bug

#629 ⬆️ (backend) upgrade to Django 3
  CHANGELOG.md
  src/backend/marsha/settings.py
  src/backend/setup.cfg
Labels: FUN Team
