Repository openfun/marsha, pull requests merged in 2020-05, with the labels that each got.

#677 🔖(minor) bump release to 3.7.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#678 🐛(backend) referer can match ALLOWED_HOSTS as a valid passport
  CHANGELOG.md
  src/backend/marsha/core/lti/__init__.py
  src/backend/marsha/core/tests/test_lti.py
Labels: bug

#680 🔖(patch) bump release to 3.7.1
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#683 ♻️(S3) use boto3 to generate upload form
  src/backend/marsha/core/api.py
  src/backend/marsha/core/tests/test_api_document.py
  src/backend/marsha/core/tests/test_api_thumbnail.py
  src/backend/marsha/core/tests/test_api_timed_text_track.py
  src/backend/marsha/core/tests/test_api_video.py
  src/backend/marsha/core/utils/s3_utils.py
  src/frontend/components/UploadForm/index.spec.tsx
  src/frontend/data/sideEffects/upload/index.spec.ts
  src/frontend/data/sideEffects/upload/index.ts
  src/frontend/types/AWSPresignedPost.ts
Labels: improvement

#650 👷(linters) lint backend source code with bandit
  .circleci/config.yml
  CHANGELOG.md
  CONTRIBUTORS.md
  Makefile
  src/backend/.bandit
  src/backend/marsha/core/lti/__init__.py
  src/backend/marsha/core/models/account.py
  src/backend/marsha/core/utils/cloudfront_utils.py
  src/backend/setup.cfg
Labels: improvement, needs review

#685 ✨(XAPI) add video title in xapi statement
  CHANGELOG.md
  src/backend/marsha/core/tests/test_xapi.py
  src/backend/marsha/core/xapi.py
Labels: improvement

#686 🔖(minor) bump release to 3.8.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#688 🐛(xapi) move video title in definition property
  CHANGELOG.md
  src/backend/marsha/core/tests/test_xapi.py
  src/backend/marsha/core/xapi.py
Labels: bug

#689 🔖(patch) bump release to 3.8.1
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team
