Repository openfun/marsha, pull requests merged in 2020-06, with the labels that each got.

#697 🔖(minor) bump release to 3.9.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: release

#704 🐛(AWS) fallback on default audio bitrate when absent in mediainfo
  CHANGELOG.md
  src/aws/lambda-encode/src/encodeVideo.js
Labels: bug, critical

#706 🔖(patch) bump release to 3.9.1
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-migrate/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#705 Synchronize scroll with active transcript sentence
  CHANGELOG.md
  CONTRIBUTORS.md
  src/frontend/components/TranscriptReader/index.tsx
  src/frontend/components/TranscriptSentence/index.spec.tsx
  src/frontend/components/TranscriptSentence/index.tsx
Labels: WIP, feature
