Repository openfun/marsha, pull requests merged in 2021-08, with the labels that each got.

#1083 ✨(back) management command to delete orphan mediapackage channels
  CHANGELOG.md
  src/backend/marsha/core/management/commands/clean_mediapackages.py
  src/backend/marsha/core/tests/test_command_clean_mediapackages.py
  src/backend/marsha/core/tests/test_utils_medialive_utils.py
  src/backend/marsha/core/utils/medialive_utils.py
  src/backend/setup.cfg
Labels: improvement

#1098 ✨(back) Add user group to admin site
  CHANGELOG.md
  src/backend/marsha/core/admin.py
Labels: improvement

#1103 ⬆️(aws) upgrade terraform to version 1
  src/aws/.terraform.lock.hcl
  src/aws/bin/terraform
  src/aws/output.tf
  src/aws/provider.tf
Labels: improvement, FUN Team

#1104 🔖(minor) bump release to 3.23.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1105 Merge overlapping played segments in xAPI logs
  CHANGELOG.md
  CONTRIBUTORS.md
  src/frontend/XAPI/VideoXAPIStatement.spec.ts
  src/frontend/XAPI/VideoXAPIStatement.ts
Labels: improvement, needs review, Frontend
