Repository openfun/marsha, pull requests merged in 2021-03, with the labels that each got.

#875 🌐(app) update i18n files
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team

#880 ♻️(back) change status in check_live_state command
  src/backend/marsha/core/management/commands/check_live_state.py
  src/backend/marsha/core/tests/test_command_check_live_state.py
Labels: improvement

#881 ✨(back) management command checking live stuck in idle
  CHANGELOG.md
  src/backend/marsha/core/management/commands/check_live_idle.py
  src/backend/marsha/core/tests/test_command_check_live_idle.py
  src/backend/marsha/settings.py
Labels: feature, improvement

#886 🐛(front) display higher resolution thumbnail available
  CHANGELOG.md
  src/frontend/components/VideoPlayer/index.spec.tsx
  src/frontend/components/VideoPlayer/index.tsx
Labels: bug

#882 ✨(back) install and configure whitenoise
  .gitignore
  CHANGELOG.md
  Dockerfile
  docker/tests/statics.sh
  src/aws/cloudfront.tf
  src/backend/marsha/core/storage.py
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/views.py
  src/backend/marsha/settings.py
  src/backend/setup.cfg
Labels: improvement

#887 🔖(minor) bump release to 3.17.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#896 🐛(back) add missing data context in site view
  src/backend/marsha/core/tests/test_views_site.py
  src/backend/marsha/core/views.py
Labels: bug

#899 📌(front) pin videojs to version 7.11.4
  src/frontend/components/LTIRoutes/index.tsx
  src/frontend/components/UploadForm/index.tsx
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: FUN Team

#905 🔖(patch) bump release to 3.17.1
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#895 🔨(ngrok) inject current ngrok url in aws configuration
  .gitignore
  CHANGELOG.md
  CONTRIBUTORS.md
  Makefile
  bin/get_ngrok_url
  docker-compose.yml
  src/aws/bin/terraform
Labels: improvement

#904 ♻️(aws) variabilize terraform env file in terraform script
  src/aws/bin/terraform
Labels: improvement
