Repository openfun/marsha, pull requests merged in 2021-07, with the labels that each got.

#1056 💄(frontend) Add a beta label on live configuration buttons
  CHANGELOG.md
  CONTRIBUTORS.md
  src/frontend/components/DashboardPaneButtons/index.tsx
  src/frontend/components/DashboardVideoLiveConfigureButton/index.tsx
Labels: easy pick, needs review

#1061 🔖(minor) bump release to 3.21.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1066 ✨(front) add confirmation before starting/stopping a live
  CHANGELOG.md
  src/frontend/components/ConfirmationLayer/index.spec.tsx
  src/frontend/components/ConfirmationLayer/index.tsx
  src/frontend/components/DashboardConfirmButton/index.spec.tsx
  src/frontend/components/DashboardConfirmButton/index.tsx
  src/frontend/components/DashboardVideoLiveStartButton/index.spec.tsx
  src/frontend/components/DashboardVideoLiveStartButton/index.tsx
  src/frontend/components/DashboardVideoLiveStopButton/index.spec.tsx
  src/frontend/components/DashboardVideoLiveStopButton/index.tsx
Labels: needs review

#1071 ♻️(make) stop ngrok before running a new ngrok-apply
  Makefile
Labels: improvement

#1072 ✨(front) only jitsi moderators can start a live
  CHANGELOG.md
  src/frontend/components/ConfirmationLayer/index.tsx
  src/frontend/components/DashboardConfirmButton/index.spec.tsx
  src/frontend/components/DashboardConfirmButton/index.tsx
  src/frontend/components/DashboardVideoLive/index.spec.tsx
  src/frontend/components/DashboardVideoLive/index.tsx
  src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx
  src/frontend/components/DashboardVideoLiveJitsi/index.tsx
  src/frontend/components/DashboardVideoLiveStartButton/index.spec.tsx
  src/frontend/components/DashboardVideoLiveStartButton/index.tsx
Labels: Frontend, improvement
