Repository openfun/marsha, pull requests merged in 2021-09, with the labels that each got.

#1114 📌(aws) pin node-fetch to version less than 3
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-mediapackage/yarn.lock
Labels: FUN Team

#1121 🔖(minor) bump release to 3.24.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1129 🔧(front) enable smacks in converse conf when websocket is used
  CHANGELOG.md
  src/frontend/types/libs/converse/index.d.ts
  src/frontend/utils/converse.spec.ts
  src/frontend/utils/converse.ts
Labels: feature

#1137 ⬆️(dependencies) Bump tmpl to version 1.0.5
  src/aws/lambda-complete/yarn.lock
  src/aws/lambda-configure/yarn.lock
  src/aws/lambda-encode/yarn.lock
  src/frontend/yarn.lock
Labels: dependencies

#1143 ⬆️(dependencies) Bump tmpl to version 1.0.5
  src/aws/lambda-elemental-routing/yarn.lock
  src/aws/lambda-medialive/yarn.lock
  src/aws/lambda-mediapackage/yarn.lock
  src/aws/lambda-migrate/yarn.lock
  src/aws/utils/update-state/yarn.lock
Labels: dependencies

#1144 🩹(back) public token has no LTI context
  CHANGELOG.md
  src/backend/marsha/core/tests/test_views_public_document.py
  src/backend/marsha/core/tests/test_views_public_video.py
  src/backend/marsha/core/tests/test_views_site.py
  src/backend/marsha/core/views.py
  src/frontend/types/jwt.ts
Labels: needs review

#1145 🐛(front) force xapi initialized action for a live video
  CHANGELOG.md
  src/frontend/Player/createVideojsPlayer.ts
Labels: bug

#1146 🐛(front) listen video play event instead of playing
  CHANGELOG.md
  src/frontend/Player/createVideojsPlayer.spec.tsx
  src/frontend/Player/createVideojsPlayer.ts
Labels: bug

#1147 ♻️(back) request initial MUC config before modifying it
  CHANGELOG.md
  src/backend/marsha/core/utils/xmpp_utils.py
Labels: improvement

#1160 ⬆️(front) bump ansi-regex to version 5.0.1
  src/aws/lambda-complete/yarn.lock
  src/aws/lambda-configure/yarn.lock
  src/aws/lambda-elemental-routing/yarn.lock
  src/aws/lambda-encode/yarn.lock
  src/aws/lambda-medialive/yarn.lock
  src/aws/lambda-mediapackage/yarn.lock
  src/aws/lambda-migrate/yarn.lock
  src/aws/utils/update-state/yarn.lock
Labels: dependencies

#1162 🔖(minor) bump release to 3.25.0
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-encode/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team
