Repository openfun/marsha, pull requests merged in 2021-11, with the labels that each got.

#1199 ⬆️(back) upgrade black to version 21.10b0
  src/backend/setup.cfg
Labels: dependencies

#1201 ✨(backend) access to videos with a scheduled date past
  CHANGELOG.md
  src/backend/marsha/core/models/video.py
  src/backend/marsha/core/tests/test_api_video.py
  src/backend/marsha/core/tests/test_lti_utils.py
Labels: feature, needs review, Backend

#1205 🔥(back) remove check_live_idle management command
  CHANGELOG.md
  src/backend/marsha/core/management/commands/check_live_idle.py
  src/backend/marsha/core/tests/test_command_check_live_idle.py
  src/backend/marsha/settings.py
Labels: improvement

#1226 ♻️(back) create chat room on first live start
  src/backend/marsha/core/api/video.py
  src/backend/marsha/core/tests/test_api_video.py
Labels: improvement
