Repository openfun/marsha, pull requests merged in 2022-11, with the labels that each got.

#1785 ✨(back) enrich playlist serializer with organization and consumer site
  CHANGELOG.md
  src/backend/marsha/core/api/playlist.py
  src/backend/marsha/core/serializers/account.py
  src/backend/marsha/core/serializers/base.py
  src/backend/marsha/core/serializers/playlist.py
  src/backend/marsha/core/tests/api/playlists/test_create.py
  src/backend/marsha/core/tests/api/playlists/test_delete.py
  src/backend/marsha/core/tests/api/playlists/test_list.py
  src/backend/marsha/core/tests/api/playlists/test_retrieve.py
  src/backend/marsha/core/tests/api/playlists/test_update.py
Labels: improvement

#1794 ♻️(back) change startTime used to filter aws logs using live started_at
  CHANGELOG.md
  src/backend/marsha/core/management/commands/check_live_state.py
  src/backend/marsha/core/tests/test_command_check_live_state.py
Labels: improvement

#1795 🐛(back) cast started_at in int in check_live_state command
  src/backend/marsha/core/management/commands/check_live_state.py
  src/backend/marsha/core/tests/test_command_check_live_state.py
Labels: bug

#1797 ✨(back) install and configure drf-spectacular to serve a swagger ui
  CHANGELOG.md
  src/backend/marsha/core/api/video.py
  src/backend/marsha/core/tests/test_api_schema.py
  src/backend/marsha/settings.py
  src/backend/marsha/urls.py
  src/backend/setup.cfg
Labels: improvement

#1796 ✨(back) add management command clean_aws_elemental_stack
  CHANGELOG.md
  src/backend/marsha/core/management/commands/clean_aws_elemental_stack.py
  src/backend/marsha/core/tests/test_command_clean_aws_elemental_stack.py
  src/backend/marsha/core/tests/test_command_clean_medialive_dev_stack.py
  src/backend/marsha/settings.py
Labels: improvement

#1807 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/lti_site/i18n/es_ES.json
  src/frontend/apps/lti_site/i18n/fr_CA.json
  src/frontend/apps/lti_site/i18n/fr_FR.json
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#1810 🔖(beta) bump release to 4.0.0-beta.11
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_tests/package.json
Labels: FUN Team

#1813 ✅(circleci) fix duplicate standalone_site duplicate test
  .circleci/config.yml
Labels: improvement, bug, easy pick, Frontend

#1821 ✨(back) enable recording when creating a BBB room instance
  CHANGELOG.md
  src/backend/marsha/bbb/tests/test_bbb_utils.py
  src/backend/marsha/bbb/utils/bbb_utils.py
Labels: improvement

#1825 🐛(backend) add missing SAML setting to use cache
  src/backend/marsha/settings.py
Labels: bug, Backend

#1831 ♻️(back) make bbb record optional on meeting creation
  src/backend/marsha/bbb/tests/test_bbb_utils.py
  src/backend/marsha/bbb/utils/bbb_utils.py
  src/backend/marsha/settings.py
Labels: improvement

#1830 ♻️(back) set lti_id and consumer_site nullable on playlist model
  src/backend/marsha/core/migrations/0058_alter_playlist_consumer_site_alter_playlist_lti_id_and_more.py
  src/backend/marsha/core/models/playlist.py
  src/backend/marsha/core/tests/test_models_playlist.py
Labels: improvement

#1826 📝(sprint) add sprint review #2 and #3
  docs/sprint-reviews/2022-09-30-sprint-review.md
  docs/sprint-reviews/2022-11-07-sprint-review.md
  docs/sprint-reviews/2022-12-01-sprint-review.md
Labels: FUN Team

#1858 🐛(backend) Renater SSO user role is a list
  src/backend/marsha/account/social_pipeline/organization.py
  src/backend/marsha/account/tests/test_social_pipeline_organization.py
  src/backend/setup.cfg
Labels: bug, Backend

#1866 🐛(back) change permission on retrieve endpoints
  CHANGELOG.md
  src/backend/marsha/.cookiecutter/{{cookiecutter.app_name}}/api.py
  src/backend/marsha/.cookiecutter/{{cookiecutter.app_name}}/tests/test_api.py
  src/backend/marsha/bbb/api.py
  src/backend/marsha/bbb/tests/api/classroom/test_retrieve.py
  src/backend/marsha/bbb/tests/api/classroom/test_service_join.py
  src/backend/marsha/deposit/api.py
  src/backend/marsha/deposit/tests/api/filedepositories/test_retrieve.py
  src/backend/marsha/markdown/tests/api/markdown_documents/test_retrieve.py
Labels: bug
