Repository openfun/marsha, pull requests merged in 2022-05, with the labels that each got.

#1526 ♻️(front) reorganize widget order in the live dashboard
  src/frontend/components/DashboardVideoLiveControlPane/index.tsx
Labels: improvement

#1531 🩹(front) fix calendar display
  src/frontend/components/SchedulingFields/index.tsx
Labels: bug, Frontend

#1536 ⬆️(front) upgrade to jest 28
  src/frontend/Player/createPlayer.spec.ts
  src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx
  src/frontend/components/PublicVideoDashboard/index.spec.tsx
  src/frontend/components/StudentLiveAdvertising/StudentLiveScheduleInfo/index.spec.tsx
  src/frontend/data/sideEffects/pollForLive/index.spec.tsx
  src/frontend/data/sideEffects/pollForTrack/index.spec.tsx
  src/frontend/jest.config.js
  src/frontend/package.json
  src/frontend/utils/resumeLive.spec.ts
  src/frontend/utils/tests/resolver.js
  src/frontend/yarn.lock
Labels: FUN Team

#1537 🔧(renovate) remove jest from ignored packages
  renovate.json
Labels: FUN Team

#1543 ♻️(aws) allow to configure allocated memory to lambda convert
  docs/env.md
  src/aws/lambda.tf
  src/aws/variables.tf
Labels: improvement

#1548 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team

#1549 🔖(beta) bump release to 4.0.0-beta.4
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1550 ✨(front) push attendance when student is on stage
  CHANGELOG.md
  src/frontend/components/StudentLiveWrapper/index.spec.tsx
  src/frontend/components/StudentLiveWrapper/index.tsx
Labels: feature

#1558 🐛(front) do not execute start streaming in jitsi for non moderator
  CHANGELOG.md
  src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx
  src/frontend/components/DashboardVideoLiveJitsi/index.tsx
Labels: bug

#1560 🐛(front) start jitsi streaming once component load and already running
  src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx
  src/frontend/components/DashboardVideoLiveJitsi/index.tsx
Labels: bug
