Repository openfun/marsha, pull requests merged in 2022-03, with the labels that each got.

#1408 speed up docker build by activating DOCKER_BUILDKIT
  .circleci/config.yml
  Makefile
  bin/lambda
Labels: improvement

#1409 🐛(docker) Preserve marsha package structure
  CHANGELOG.md
  Dockerfile
  docker/images/dev/Dockerfile
  docker/images/e2e/Dockerfile
Labels: bug

#1411 Bugfix/qbey/dockerfile preserve marsha package
  docker/images/dev/Dockerfile
  docker/images/e2e/Dockerfile
Labels: bug

#1413 🔧(docker) restrict what is copied in the production image
  .dockerignore
  Dockerfile
  docker/files/usr/local/bin/entrypoint
Labels: improvement

#1417 💚(front) add missing snapshots
  src/frontend/components/Chat/SharedChatComponents/InputBar/__image_snapshots__/index-spec-tsx-input-bar-ui-displays-the-component-in-not-chat-input-format-with-little-width-for-text-placeholder-ellipsis-and-compares-it-with-previous-renders-1-snap.png
  src/frontend/components/SVGIcons/__image_snapshots__/index-spec-tsx-svg-icon-renders-svg-icon-component-correctly-1-snap.png
Labels: FUN Team

#1414 🐛(frontend) fix converse initialisation
  src/frontend/components/Chat/index.spec.tsx
  src/frontend/components/Chat/index.tsx
  src/frontend/components/Chat/route.ts
  src/frontend/components/ConverseInitializer/index.spec.tsx
  src/frontend/components/ConverseInitializer/index.tsx
  src/frontend/components/DashboardVideoLive/index.spec.tsx
  src/frontend/components/DashboardVideoLive/index.tsx
  src/frontend/components/LTIRoutes/index.tsx
  src/frontend/components/LiveVideoPanel/index.spec.tsx
  src/frontend/components/LiveVideoPanel/index.tsx
  src/frontend/components/PublicVideoDashboard/index.spec.tsx
  src/frontend/components/PublicVideoLiveJitsi/index.spec.tsx
  src/frontend/components/StudentLiveWrapper/index.spec.tsx
  src/frontend/components/StudentLiveWrapper/index.tsx
  src/frontend/utils/conversejs/converse.ts
Labels: bug

#1424 🐛(front) keep input register email display
  src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.spec.tsx
  src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.tsx
Labels: bug

#1432 🐛(back) expose XMPP info for a live once this one started
  CHANGELOG.md
  src/backend/marsha/core/serializers/video.py
  src/backend/marsha/core/tests/test_api_video.py
  src/backend/marsha/core/tests/test_views_lti_video.py
Labels: bug

#1435 🔥(front) remove RTMP info in the teacher dashboard
  src/frontend/components/DashboardVideoLiveInfo/index.spec.tsx
  src/frontend/components/DashboardVideoLiveInfo/index.tsx
  src/frontend/components/DashboardVideoLiveJitsi/index.tsx
Labels: improvement

#1464 🐛(back) continue stopping live even if input waiter fails
  CHANGELOG.md
  src/backend/marsha/core/tests/test_utils_medialive_utils.py
  src/backend/marsha/core/utils/medialive_utils.py
  src/backend/marsha/settings.py
Labels: bug

#1465 🔧(front) disable jitsi prejoin page
  CHANGELOG.md
  src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx
  src/frontend/components/DashboardVideoLiveJitsi/index.tsx
Labels: improvement

#1467 🔨(dev) limit iframe width
  src/backend/marsha/core/templates/core/lti_development.html
Labels: improvement
