Repository openfun/marsha, pull requests merged in 2022-06, with the labels that each got.

#1573 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team

#1574 🔖(beta) bump release to 4.0.0-beta.5
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1589 Share document with picture in picture (student side)
  CHANGELOG.md
  src/frontend/components/StudentLiveWrapper/UpdateCurrentSharedLiveMediaPage/index.spec.tsx
  src/frontend/components/StudentLiveWrapper/UpdateCurrentSharedLiveMediaPage/index.tsx
  src/frontend/components/StudentLiveWrapper/index.spec.tsx
  src/frontend/components/StudentLiveWrapper/index.tsx
Labels: feature, Frontend

#1352 Manage chat exceptions and some minor errors
  src/frontend/utils/conversejs/converse-plugins/chatPlugin.ts
Labels: bug, Frontend

#1600 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team

#1604 🔖(beta) bump release to 4.0.0-beta.6
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1613 📝(core) fix changelog section
  CHANGELOG.md
Labels: FUN Team

#1591 Configure rest framework throttling
  src/backend/marsha/settings.py
Labels: improvement

#1615 ♻️(markdown) rename route in markdown-documents
  CHANGELOG.md
  src/backend/marsha/core/templates/core/lti_development.html
  src/backend/marsha/markdown/api.py
  src/backend/marsha/markdown/models.py
  src/backend/marsha/markdown/tests/test_api.py
  src/backend/marsha/markdown/tests/test_views_lti.py
  src/backend/marsha/markdown/urls.py
  src/frontend/apps/markdown/types/models.ts
Labels: improvement

#1612 🐛(back) missing migration migrating video upload_state and live_state data
  CHANGELOG.md
  src/backend/marsha/core/migrations/0051_migrate_live_state.py
Labels: bug

#1617 ♻️(front) enable participants and share video in jitsi for everybody
  src/frontend/components/DashboardVideoLive/index.tsx
  src/frontend/components/DashboardVideoLiveJitsi/utils.spec.ts
  src/frontend/components/DashboardVideoLiveJitsi/utils.ts
Labels: improvement

#1620 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team

#1621 🔖(beta) bump release to 4.0.0-beta.7
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1622 ⚡️(front) clean websockets in test to speed them
  src/frontend/data/websocket.spec.ts
Labels: improvement
