Repository openfun/marsha, pull requests merged in 2022-04, with the labels that each got.

#1472 ⬆️(aws) upgrade @openfun/subsrt to version 1.0.5
  src/aws/lambda-convert/package.json
  src/aws/lambda-convert/yarn.lock
Labels: dependencies

#1478 🐛(back) dispatch video in the websocket when start/stop recording
  CHANGELOG.md
  src/backend/marsha/core/api/video.py
  src/backend/marsha/core/tests/test_api_video_recording.py
Labels: bug, critical

#1486 ⚰️(back) remove video constraint video_unique_idx
  CHANGELOG.md
  src/backend/marsha/core/migrations/0043_remove_video_video_unique_idx.py
  src/backend/marsha/core/models/video.py
  src/backend/marsha/core/tests/test_models_video.py
Labels: FUN Team

#1488 🩹(front) fix avatar icon's crushed width in chat
  src/frontend/components/Chat/SharedChatComponents/ChatMessageMetadatas/index.tsx
Labels: bug, Frontend

#1491 ♻️(i18n) emails must be generated before the i18n job
  .circleci/config.yml
Labels: needs review

#1493 🌐(i18n) update translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team

#1495 🔖(beta) bump release to 4.0.0-beta.2
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1497 🔧(ci) attach workspace in build-back-i18n job
  .circleci/config.yml
Labels: FUN Team

#1508 🔥(front) remove presence activity in the chat
  CHANGELOG.md
  src/frontend/components/Chat/SharedChatComponents/ChatConversationDisplayer/__image_snapshots__/index-spec-tsx-chat-conversation-displayer-renders-components-with-messages-and-presences-and-compares-it-with-previous-render-1-snap.png
  src/frontend/components/Chat/SharedChatComponents/ChatConversationDisplayer/index.spec.tsx
  src/frontend/components/Chat/SharedChatComponents/ChatConversationDisplayer/index.tsx
  src/frontend/components/Chat/SharedChatComponents/ChatPresenceItem/__image_snapshots__/index-spec-tsx-chat-presence-item-renders-the-component-and-compares-it-with-a-previous-render-for-a-departure-presence-1-snap.png
  src/frontend/components/Chat/SharedChatComponents/ChatPresenceItem/__image_snapshots__/index-spec-tsx-chat-presence-item-renders-the-component-and-compares-it-with-a-previous-render-for-an-arrival-presence-1-snap.png
  src/frontend/components/Chat/SharedChatComponents/ChatPresenceItem/index.spec.tsx
  src/frontend/components/Chat/SharedChatComponents/ChatPresenceItem/index.tsx
  src/frontend/data/stores/useChatItemsStore/index.spec.tsx
  src/frontend/data/stores/useChatItemsStore/index.ts
  src/frontend/utils/conversejs/converse-plugins/chatPlugin.ts
Labels: improvement

#1509 🌐(i18n) update translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team
