Repository openfun/marsha, pull requests merged in 2022-07, with the labels that each got.

#1631 🔨(front) allow to disable chrome sandboxing with puppeteer
  CHANGELOG.md
  src/frontend/utils/tests/imageSnapshot.tsx
Labels: improvement

#1646 ♻️(front) remove use of Roboto-Regular
  src/frontend/apps/bbb/DashboardClassroom/index.tsx
  src/frontend/components/Chat/InputBar/index.tsx
  src/frontend/components/Chat/JoinChatButton/index.tsx
  src/frontend/components/DashboardVideoLiveControlPane/customs/DashboardVideoLiveInfoModal/index.tsx
  src/frontend/components/DashboardVideoLiveControlPane/inputs/DashboardVideoLiveWidgetTextAreaInput/index.tsx
  src/frontend/components/DashboardVideoLiveControlPane/inputs/DashboardVideoLiveWidgetTextInput/index.tsx
  src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetSchedulingAndDescription/index.tsx
  src/frontend/components/StudentLiveAdvertising/index.tsx
Labels: Frontend

#1654 🐛(front) redirect to the VOD dashboard when the live_state is ended
  CHANGELOG.md
  src/frontend/components/Dashboard/DashboardVideoWrapper/index.spec.tsx
  src/frontend/components/Dashboard/DashboardVideoWrapper/index.tsx
Labels: bug
