Repository openfun/marsha, pull requests merged in 2022-01, with the labels that each got.

#1287 👷(yarn) prevent old cache usage for js dependencies
  .circleci/config.yml
Labels: dependencies

#1290 Ignore react router in renovate
  renovate.json
Labels: dependencies

#1300 🔥(back) remove user id in prosody JWT token
  CHANGELOG.md
  src/backend/marsha/core/serializers/video.py
  src/backend/marsha/core/tests/test_api_video.py
  src/backend/marsha/core/tests/test_utils_xmpp_utils.py
  src/backend/marsha/core/utils/xmpp_utils.py
Labels: improvement

#1303 🎨(make) change help task to better display self documenting makefile
  Makefile
Labels: improvement

#1307 Add default config for the chat
  CHANGELOG.md
  src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.spec.tsx
  src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.tsx
  src/frontend/default/chat.ts
  src/frontend/utils/chat/chat.spec.ts
  src/frontend/utils/chat/chat.ts
Labels: Frontend

#1305 ✨(email) mail sent when registering to a scheduled webinar
  CHANGELOG.md
  src/backend/marsha/core/api/live_registration.py
  src/backend/marsha/core/tests/test_api_liveregistration.py
  src/backend/marsha/settings.py
  src/mail/mjml/sample.mjml
Labels: needs review

#1328 ♻️(front) use @converse/headless instead of converse.js
  src/frontend/package.json
  src/frontend/utils/conversejs/converse.ts
  src/frontend/utils/conversejs/entry.js
  src/frontend/yarn.lock
Labels: improvement

#1329 👷(circle) increase jest worker to 2
  .circleci/config.yml
Labels: improvement

#1331 🔨(make) add reset task
  Makefile
Labels: improvement

#1333 🔨(command) add a development command to simulate emails
  src/backend/marsha/core/management/commands/dev_simulate_reminders.py
  src/backend/marsha/core/tests/test_command_dev_simulate_reminders.py
  src/backend/marsha/core/tests/test_command_send_reminders.py
Labels: needs review

#1338 📌(front) pin @converse/headless to version 8.0.1
  renovate.json
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependencies
