Repository openfun/marsha, pull requests merged in 2022-10, with the labels that each got.

#1750 Increase classroom form debounce time
  CHANGELOG.md
  src/frontend/apps/lti_site/apps/classroom/components/DashboardClassroomForm/index.tsx
Labels: needs review

#1767 📝(frontend) add standalone site startup
  README.md
Labels: Site

#1768 ♻️(front) adapt cookiecutter with new SelectContent
  src/frontend/apps/lti_site/apps/.cookiecutter/cookiecutter.json
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/Routes.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContent/SelectContentResource/index.spec.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContent/SelectContentResource/index.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContent/SelectContentSection/index.spec.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContent/SelectContentSection/index.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContent/SelectContentTab/index.spec.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContent/SelectContentTab/index.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContent/commonMessages.ts
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContentTab/index.spec.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/SelectContentTab/index.tsx
  src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/types/{{cookiecutter.app_name_capitalized}}AppData.ts
Labels: FUN Team

#1771 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/lti_site/i18n/es_ES.json
  src/frontend/apps/lti_site/i18n/fr_CA.json
  src/frontend/apps/lti_site/i18n/fr_FR.json
Labels: FUN Team

#1774 🔖(beta) bump release to 4.0.0-beta.9
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
Labels: FUN Team
