Repository openfun/marsha, pull requests merged in 2022-12, with the labels that each got.

#1869 🧑‍💻(github) improve bug report issue template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: FUN Team

#1881 🚨(front) fix DashboardClassroomForm test
  src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.spec.tsx
Labels: bug

#1874 🐛(front) deal with webinar without thumbnail
  CHANGELOG.md
  src/frontend/apps/lti_site/components/VideoPlayer/index.spec.tsx
  src/frontend/apps/lti_site/components/VideoPlayer/index.tsx
Labels: bug

#1885 🐛(back) force to save the starting live state on the start action
  CHANGELOG.md
  src/backend/marsha/core/api/video.py
  src/backend/marsha/core/tests/test_api_video.py
Labels: bug

#1894 🐛(front) guess ISO15897 locale code in standalone site
  CHANGELOG.md
  src/frontend/apps/standalone_site/src/App.spec.tsx
  src/frontend/apps/standalone_site/src/App.tsx
  src/frontend/apps/standalone_site/src/conf/global.ts
  src/frontend/apps/standalone_site/src/utils/lang.spec.ts
  src/frontend/apps/standalone_site/src/utils/lang.ts
Labels: bug

#1883 🐛(lti) fix translation number of viewers
  CHANGELOG.md
  src/frontend/apps/lti_site/components/LiveInfoBar/index.spec.tsx
  src/frontend/apps/lti_site/components/LiveInfoBar/index.tsx
Labels: improvement

#1904 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/lti_site/i18n/es_ES.json
  src/frontend/apps/lti_site/i18n/fr_CA.json
  src/frontend/apps/lti_site/i18n/fr_FR.json
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#1908 🔖(beta) bump release to 4.0.0-beta.12
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_tests/package.json
Labels: FUN Team
