Repository openfun/marsha, pull requests merged in 2022-02, with the labels that each got.

#1340 🐛(front) better detect https protocol to connect to the websocket
  src/frontend/data/websocket.spec.ts
  src/frontend/data/websocket.ts
Labels: bug

#1341 🩹(front) fix stream stanza raising an error
  src/frontend/utils/conversejs/converse-plugins/chatPlugin.ts
Labels: bug, Frontend

#1356 🐛(front) fix unscrollable viewers list in tabs
  src/frontend/components/StudentViewersList/index.tsx
Labels: bug, Frontend

#1357 🐛(front) fix unscrollable chat messages in instructor view
  src/frontend/components/Chat/index.tsx
  src/frontend/components/DashboardVideoLiveRunning/index.tsx
Labels: bug, Frontend

#1362 🔧(front) update converse initialization settings
  src/frontend/types/libs/converse/index.d.ts
  src/frontend/utils/conversejs/converse.spec.ts
  src/frontend/utils/conversejs/converse.ts
Labels: improvement, Frontend

#1363 ✨(front) address server's answer when entering an displayName
  CHANGELOG.md
  src/frontend/components/Chat/SharedChatComponents/InputBar/index.spec.tsx
  src/frontend/components/Chat/SharedChatComponents/InputBar/index.tsx
  src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.spec.tsx
  src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.tsx
  src/frontend/components/Chat/StudentChat/index.spec.tsx
  src/frontend/default/chat.ts
  src/frontend/types/libs/converse/index.d.ts
  src/frontend/utils/conversejs/converse-plugins/nicknameManagementPlugin.ts
Labels: feature, Frontend

#1372 ⬆️(aws) Bump ajv to 6.12.6
  src/aws/lambda-complete/yarn.lock
  src/aws/lambda-convert/yarn.lock
  src/aws/lambda-medialive/yarn.lock
  src/aws/utils/update-state/yarn.lock
Labels: dependencies

#1374 🌐(i18n) update translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/i18n/es_ES.json
  src/frontend/i18n/fr_CA.json
  src/frontend/i18n/fr_FR.json
Labels: FUN Team

#1375 ♻️(back) configure with settings the default lti locale
  CHANGELOG.md
  src/backend/marsha/core/lti/__init__.py
  src/backend/marsha/core/tests/test_lti.py
  src/backend/marsha/settings.py
Labels: improvement

#1376 🔧(back) allow to configure CSRF_TRUSTED_ORIGINS django setting
  CHANGELOG.md
  src/backend/marsha/settings.py
Labels: improvement

#1377 🔖(major) bump release to 4.0.0-beta.1
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/package.json
Labels: FUN Team

#1378 ✨(back) unsubscribe from reminders for scheduled webinars
  CHANGELOG.md
  env.d/development.dist
  env.d/test
  src/backend/marsha/core/admin.py
  src/backend/marsha/core/api/live_registration.py
  src/backend/marsha/core/management/commands/send_reminders.py
  src/backend/marsha/core/migrations/0035_auto_20220216_1713.py
  src/backend/marsha/core/models/video.py
  src/backend/marsha/core/templates/core/reminder_unregister.html
  src/backend/marsha/core/tests/test_api_liveregistration.py
  src/backend/marsha/core/tests/test_command_send_reminders.py
  src/backend/marsha/core/tests/test_models_liveregistration.py
  src/backend/marsha/core/tests/test_views_reminders_cancel.py
  src/backend/marsha/core/utils/api_utils.py
  src/backend/marsha/core/views.py
  src/backend/marsha/settings.py
  src/backend/marsha/urls.py
  src/mail/mjml/partial/footer.mjml
Labels: feature, needs review

#1381 🐛(back) allow to configure converse persistent store
  CHANGELOG.md
  src/backend/marsha/core/serializers/video.py
  src/backend/marsha/core/tests/test_api_video.py
  src/backend/marsha/core/tests/test_api_video_shared_live_media.py
  src/backend/marsha/core/tests/test_views_lti_video.py
  src/backend/marsha/core/tests/test_views_public_video.py
  src/backend/marsha/settings.py
  src/frontend/components/Chat/index.spec.tsx
  src/frontend/components/LiveVideoPanel/index.spec.tsx
  src/frontend/components/PublicVideoDashboard/index.spec.tsx
  src/frontend/components/PublicVideoLiveJitsi/index.spec.tsx
  src/frontend/components/StudentLiveControlBar/index.spec.tsx
  src/frontend/components/StudentLiveWrapper/index.spec.tsx
  src/frontend/components/VideoPlayer/index.spec.tsx
  src/frontend/types/XMPP.ts
  src/frontend/types/libs/converse/index.d.ts
  src/frontend/utils/conversejs/converse.spec.ts
  src/frontend/utils/conversejs/converse.ts
Labels: bug, critical
