Repository openfun/marsha, pull requests merged in 2023-05, with the labels that each got.

#2214 🔖(major) bump release to 4.0.0
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-complete/yarn.lock
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-convert/yarn.lock
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-medialive/yarn.lock
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-mediapackage/yarn.lock
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
Labels: FUN Team

#2219 📌(front) manage packages version in main package.json resolutions
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
Labels: dependencies

#2222 ⬆️(tray) use batch/v1 api in cronjob_pipeline manifest
  CHANGELOG.md
  src/tray/templates/services/app/cronjob_pipeline.yml.j2
Labels: improvement

#2227 ✨(lib-video) lti code to copy to clipboard
  CHANGELOG.md
  src/frontend/packages/lib_components/src/common/WidgetsContainer/InfoModal/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VisibilityAndInteraction/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VisibilityAndInteraction/index.tsx
Labels: easy pick, feature request, Frontend, Site

#2239 🔧(back) configure SOCIAL_AUTH_LOGIN_ERROR_URL setting
  CHANGELOG.md
  src/backend/marsha/settings.py
Labels: improvement

#2251 ✨(back) add a middleware to deal with social auth exception
  CHANGELOG.md
  src/backend/marsha/account/middleware.py
  src/backend/marsha/account/tests/test_middleware.py
  src/backend/marsha/account/tests/test_social_pipeline_organization.py
  src/backend/marsha/account/tests/utils.py
  src/backend/marsha/settings.py
Labels: improvement

#2260 🔧(back) enable sentry performance and profiling in django
  CHANGELOG.md
  src/backend/marsha/settings.py
Labels: improvement

#2261 🔖(major) bump release to 4.1.0
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
Labels: FUN Team

#2264 🐛(front) remove initial / from page slug to use it in the API fetch
  CHANGELOG.md
  src/frontend/apps/standalone_site/src/features/PagesApi/components/PagesApi.spec.tsx
  src/frontend/apps/standalone_site/src/features/PagesApi/components/PagesApi.tsx
Labels: bug

#2265 🐛(frontend) fix potential side effect with refreshToken
  CHANGELOG.md
  src/frontend/packages/lib_components/src/common/queries/fetchReconnectWrapper.tsx
  src/frontend/packages/lib_components/src/data/sideEffects/refreshToken/index.spec.ts
  src/frontend/packages/lib_components/src/data/sideEffects/refreshToken/index.ts
  src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.spec.tsx
  src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.ts
  src/frontend/packages/lib_components/src/utils/system.ts
Labels: improvement, bug, Frontend

#2263 Generate an ICS file when a classroom is scheduled
  CHANGELOG.md
  src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.spec.tsx
  src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.tsx
Labels: feature, Frontend
