Repository openfun/marsha, pull requests merged in 2023-04, with the labels that each got.

#2162 🐛(front) correctly fetch transcript content in TranscriptReader
  CHANGELOG.md
  src/frontend/packages/lib_video/src/api/useTranscriptReaderRequest/index.ts
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/Transcripts/TranscriptReader/index.tsx
Labels: bug

#2175 ✨(website) add disabled button create ressource form
  CHANGELOG.md
  src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.spec.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.tsx
  src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.spec.tsx
  src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.tsx
Labels: improvement, easy pick, feature, Frontend, Site

#2177 ⬆️(back) upgrade to django 4.1
  .circleci/config.yml
  docker-compose.yml
  renovate.json
  src/backend/marsha/bbb/api.py
  src/backend/marsha/bbb/migrations/0012_alter_classroomdocument_options.py
  src/backend/marsha/bbb/models.py
  src/backend/marsha/bbb/tests/api/classroom/test_classroomdocuments.py
  src/backend/marsha/bbb/tests/api/classroom/test_update.py
  src/backend/marsha/bbb/tests/api/classroomdocument/test_create.py
  src/backend/marsha/bbb/tests/api/classroomdocument/test_initiate_upload.py
  src/backend/marsha/bbb/tests/bbb_utils/test_create.py
  src/backend/marsha/bbb/tests/test_utils_tokens.py
  src/backend/marsha/core/admin.py
  src/backend/marsha/core/migrations/0061_remove_video_live_type_check_video_live_type_check.py
  src/backend/marsha/core/models/base.py
  src/backend/marsha/core/models/video.py
  src/backend/marsha/core/serializers/video.py
  src/backend/marsha/core/tests/api/live_sessions/test_create.py
  src/backend/marsha/core/tests/api/live_sessions/test_update.py
  src/backend/marsha/core/tests/api/shared_live_media/test_initiate_upload.py
  src/backend/marsha/core/tests/api/shared_live_media/test_list.py
  src/backend/marsha/core/tests/api/shared_live_media/test_retrieve.py
  src/backend/marsha/core/tests/api/thumbnails/test_initiate_upload.py
  src/backend/marsha/core/tests/api/thumbnails/test_retrieve.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_initiate_upload.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_retrieve.py
  src/backend/marsha/core/tests/api/video/test_initiate_live.py
  src/backend/marsha/core/tests/api/video/test_initiate_upload.py
  src/backend/marsha/core/tests/api/video/test_list.py
  src/backend/marsha/core/tests/api/video/test_retrieve.py
  src/backend/marsha/core/tests/api/video/test_start_live.py
  src/backend/marsha/core/tests/api/video/test_stop_live.py
  src/backend/marsha/core/tests/api/video/test_update_live_state.py
  src/backend/marsha/core/tests/management_commands/test_send_reminders.py
  src/backend/marsha/core/tests/models/test_video.py
  src/backend/marsha/core/tests/serializers/test_base.py
  src/backend/marsha/core/tests/serializers/test_update_state.py
  src/backend/marsha/core/tests/test_api_document.py
  src/backend/marsha/core/tests/utils/test_medialive_utils.py
  src/backend/marsha/core/tests/utils/test_time_utils.py
  src/backend/marsha/core/utils/time_utils.py
  src/backend/marsha/deposit/migrations/0005_alter_depositedfile_options.py
  src/backend/marsha/deposit/models.py
  src/backend/marsha/deposit/tests/api/depositedfiles/test_initiate_upload.py
  src/backend/marsha/deposit/tests/api/filedepositories/test_depositedfiles.py
  src/backend/marsha/markdown/tests/api/markdown_images/test_initiate_upload.py
  src/backend/marsha/markdown/tests/api/markdown_images/test_retrieve.py
  src/backend/setup.cfg
Labels: dependencies

#2190 ⬇️(back) downgrade django to version 4.1
  CHANGELOG.md
  UPGRADE.md
  docs/env.md
  renovate.json
  src/backend/marsha/core/tests/test_statics.py
  src/backend/marsha/settings.py
  src/backend/setup.cfg
Labels: FUN Team

#2193 🐛(front) extract DashboardContent from VODTeacherDashboard
  src/frontend/packages/lib_video/src/components/vod/Teacher/Dashboard.tsx
Labels: bug

#2194 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/backend/marsha/e2e/test_lti_bbb.py
  src/backend/marsha/e2e/test_site.py
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Update/LiveUpdate.spec.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Update/LiveUpdate.tsx
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
  src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/ToolsAndApplications/index.tsx
  src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.spec.tsx
  src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.tsx
Labels: FUN Team

#2196 🔖(beta) bump release to 4.0.0-beta.19
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-complete/yarn.lock
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-convert/yarn.lock
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-medialive/yarn.lock
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-mediapackage/yarn.lock
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
Labels: FUN Team

#2197 ⬇️(back) downgrade python social auth to version 4.3.0
  CHANGELOG.md
  src/backend/setup.cfg
Labels: bug, critical

#2198 🔖(beta) bump release to 4.0.0-beta.20
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-complete/yarn.lock
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-convert/yarn.lock
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-medialive/yarn.lock
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-mediapackage/yarn.lock
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
Labels: FUN Team

#2212 🐛(site) remove creation playlist in content filter
  src/frontend/apps/standalone_site/src/features/Contents/components/ContentsFilter/ContentsFilter.spec.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.spec.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreateForm.spec.tsx
  src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreateForm.tsx
  src/frontend/apps/standalone_site/src/features/Playlist/hooks/useSelectPlaylist.spec.tsx
  src/frontend/apps/standalone_site/src/features/Playlist/hooks/useSelectPlaylist.tsx
Labels: bug

#2211 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team
