Repository openfun/marsha, pull requests merged in 2023-10, with the labels that each got.

#2435 ♻️(frontend) replace Paragraph grommet
  CHANGELOG.md
  src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardInstructor/index.tsx
  src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/UploadFiles/index.tsx
  src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/index.tsx
  src/frontend/apps/lti_site/components/PortabilityRequest/index.tsx
  src/frontend/apps/standalone_site/src/features/Playlist/features/UpdatePlaylist/components/AddUserAccessForm.tsx
  src/frontend/apps/standalone_site/src/features/Playlist/features/UpdatePlaylist/components/SearchUserList.tsx
  src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/SupportSharing/UploadDocuments/index.tsx
  src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.tsx
  src/frontend/packages/lib_common/cunningham.ts
  src/frontend/packages/lib_common/src/cunningham/cunningham-tokens.css
  src/frontend/packages/lib_common/src/theme.ts
  src/frontend/packages/lib_components/src/common/ErrorComponents/BoundaryScreenError/index.tsx
  src/frontend/packages/lib_components/src/common/ErrorComponents/FullscreenError/index.tsx
  src/frontend/packages/lib_components/src/common/Widgets/RetentionDate/index.tsx
  src/frontend/packages/lib_components/src/common/WidgetsContainer/InfoModal/index.tsx
  src/frontend/packages/lib_video/src/components/common/DashboardControlPane/DashboardLiveTabAttendance/DashboardLiveTabAttendanceWaiting/index.tsx
  src/frontend/packages/lib_video/src/components/common/PictureInPictureLayer/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoInfoBar/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/Transcripts/TranscriptReader/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VODCreation/HarvestVOD/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VODCreation/PublishVOD/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VODCreation/index.tsx
  src/frontend/packages/lib_video/src/components/live/Student/StudentLiveError/index.tsx
  src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveAdvertising/StudentLiveDescription/index.tsx
  src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.tsx
  src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveAdvertising/StudentLiveRegistration/index.tsx
  src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveAdvertising/StudentLiveScheduleInfo/index.tsx
  src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveAdvertising/index.tsx
  src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveWaitingRoom/index.tsx
  src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/Controls/TeacherLiveLifecycleControls/StartLiveButton/index.tsx
  src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/Controls/TeacherLiveLifecycleControls/StopLiveButton/index.tsx
  src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/Controls/TeacherLiveLifecycleControls/index.tsx
  src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/TeacherLiveTypeSwitch/index.tsx
  src/frontend/packages/lib_video/src/components/live/common/DashboardLiveRaw/index.tsx
  src/frontend/packages/lib_video/src/components/live/common/ViewersList/index.tsx
Labels: improvement, easy pick, Frontend

#2455 🔊(changelog) move changelog to correct version
  CHANGELOG.md
Labels: easy pick

#2464 ♻️(front) increase classroom poll refetch interval
  src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx
Labels: improvement

#2477 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/lti_site/i18n/es_ES.json
  src/frontend/apps/lti_site/i18n/fr_CA.json
  src/frontend/apps/lti_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#2478 🔖(minor) bump release to 4.7.0
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
  src/webtorrent/package.json
Labels: FUN Team
