Repository openfun/marsha, pull requests merged in 2023-08, with the labels that each got.

#2297 ✨(frontend) integrate cunningham
  CHANGELOG.md
  src/frontend/apps/lti_site/index.tsx
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/apps/standalone_site/src/index.tsx
  src/frontend/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_common/src/cunningham-style.css
  src/frontend/packages/lib_common/src/cunningham-tokens.css
  src/frontend/yarn.lock
Labels: improvement, feature, Frontend

#2361 ♻️(back) redirect to matching site on complete shibboleth route
  src/backend/marsha/account/tests/test_views.py
  src/backend/marsha/account/views.py
Labels: improvement

#2362 ⬆️(dockerfile) switch from debian bullseye to bookworm
  Dockerfile
Labels: improvement

#2363 ➖(back) remove lxml dependency management
  renovate.json
  src/backend/setup.cfg
Labels: improvement

#2375 💄(website) add padding on renater select field
  src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.tsx
Labels: easy pick, Frontend

#2382 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/lti_site/i18n/es_ES.json
  src/frontend/apps/lti_site/i18n/fr_CA.json
  src/frontend/apps/lti_site/i18n/fr_FR.json
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#2381 📝(backend) define clearly the role of the inner access token in deep linking
  CONTRIBUTORS.md
  src/backend/marsha/core/simple_jwt/tokens.py
Labels: improvement

#2380 ♿️(frontend) remove redundant form role in the LTI app
  src/frontend/apps/lti_site/components/SelectContent/index.tsx
Labels: bug, easy pick

#2389 Change downloading statements category related activity
  CHANGELOG.md
  src/backend/marsha/core/tests/test_xapi.py
  src/backend/marsha/core/tests/xapi/document/test_statement_from_website.py
  src/backend/marsha/core/xapi.py
Labels: bug, needs review

#2392 🐛(front) display claim link only when is-claimed request succeeded
  CHANGELOG.md
  src/frontend/apps/lti_site/components/ClaimLink/index.spec.tsx
  src/frontend/apps/lti_site/components/ClaimLink/index.tsx
Labels: bug

#2393 🔖(fix) bump release to 4.3.1
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
  src/webtorrent/package.json
Labels: FUN Team
