Repository openfun/marsha, pull requests merged in 2023-07, with the labels that each got.

#2306 🐛(frontend) problem router on upload document
  src/frontend/apps/lti_site/components/LTIRoutes/index.spec.tsx
  src/frontend/apps/lti_site/components/LTIRoutes/index.tsx
  src/frontend/apps/lti_site/components/PlaylistPortability/route.ts
  src/frontend/apps/lti_site/components/VideoWizard/index.tsx
  src/frontend/packages/lib_components/src/common/UploadForm/index.tsx
  src/frontend/packages/lib_components/src/common/UploadForm/route.ts
Labels: bug, easy pick, Frontend

#2348 🔧(tray) use webtorrent master image
  src/tray/vars/all/main.yml
Labels: FUN Team

#2310 🐛(frontend) fix problem panel chat on live
  CHANGELOG.md
  src/frontend/packages/lib_components/src/utils/useResizer.tsx
  src/frontend/packages/lib_video/src/components/common/VideoLayout/index.tsx
Labels: bug, easy pick, Frontend, Site

#2349 🐛(webtorrent) fix jsonwebtoken import
  src/webtorrent/src/verifyClient.ts
Labels: bug

#2351 🔧(tray) change webtorrent container name and pull policy
  src/tray/templates/services/webtorrent/deploy.yml.j2
Labels: improvement

#2353 🐛(back) use django.conf module to import settings instead of marsha
  src/backend/marsha/core/models/playlist.py
  src/backend/marsha/core/tests/models/test_retention_date_object_mixin.py
Labels: bug

#2357 ✨(tray) manage multiple ingresses
  CHANGELOG.md
  src/tray/templates/services/app/_deploy_base.yml.j2
  src/tray/templates/services/app/job_db_migrate.yml.j2
  src/tray/templates/services/nginx/ingress.yml.j2
  src/tray/vars/all/main.yml
Labels: improvement
