Repository openfun/marsha, pull requests merged in 2023-01, with the labels that each got.

#1928 🐛(frontend) create unique storage name for useJwt hook
  CHANGELOG.md
  src/frontend/apps/lti_site/components/App/index.tsx
Labels: bug

#1917 🐛(lti) refresh live parameters state
  CHANGELOG.md
  src/frontend/apps/lti_site/components/InstructorWrapper/InstructorView/index.tsx
  src/frontend/apps/lti_site/components/LiveInfoBar/index.tsx
  src/frontend/apps/lti_site/components/PublicVideoDashboard/PublicVODDashboard/index.spec.tsx
  src/frontend/apps/lti_site/components/VideoWidgetProvider/index.spec.tsx
  src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SchedulingAndDescription/index.tsx
  src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SharedLiveMedia/index.tsx
  src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/TitleAndDescriptionWidget/index.tsx
  src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/ToolsAndApplications/index.tsx
  src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/VisibilityAndInteraction/index.tsx
Labels: bug

#1930 🔥(front) remove Homepage text in Homepage component
  src/frontend/apps/standalone_site/src/App.spec.tsx
  src/frontend/apps/standalone_site/src/features/HomePage/components/HomePage.spec.tsx
  src/frontend/apps/standalone_site/src/features/HomePage/components/HomePage.tsx
Labels: improvement

#1931 🐛(front) display valid webinar url when creating one with LTI select
  CHANGELOG.md
  src/frontend/apps/lti_site/components/LTIRoutes/index.tsx
  src/frontend/apps/lti_site/components/SelectContent/SelectContentTargetedResource/index.tsx
  src/frontend/apps/lti_site/components/SelectContent/index.tsx
  src/frontend/packages/lib_components/src/types/AppData.ts
Labels: bug

#1929 ♻️(front) display current user full name instead of John Doe
  CHANGELOG.md
  src/frontend/apps/standalone_site/src/App.spec.tsx
  src/frontend/apps/standalone_site/src/features/Header/Header.spec.tsx
  src/frontend/apps/standalone_site/src/features/Header/Header.tsx
  src/frontend/packages/lib_components/src/utils/tests/factories.ts
Labels: improvement

#1962 📱(website) improve renater select box
  CHANGELOG.md
  src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.tsx
Labels: Frontend, Site

#1971 🐛(front) move jwt store initialization in LTI to AppInitializer
  src/frontend/apps/lti_site/components/App/AppInitializer/index.spec.tsx
  src/frontend/apps/lti_site/components/App/AppInitializer/index.tsx
  src/frontend/apps/lti_site/components/App/index.tsx
Labels: bug

#1973 🔊(front) remove unwanted console.log
  src/frontend/apps/standalone_site/src/features/Profile/features/AccountSettings/utils.ts
Labels: FUN Team

#1975 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/lti_site/i18n/es_ES.json
  src/frontend/apps/lti_site/i18n/fr_CA.json
  src/frontend/apps/lti_site/i18n/fr_FR.json
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#1976 🔖(beta) bump release to 4.0.0-beta.13
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
Labels: FUN Team

#1986 Change docker env name in circle config and optimize e2e jobs
  .circleci/config.yml
Labels: improvement

#1989 🔖(beta) bump release to 4.0.0-beta.14
  CHANGELOG.md
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
Labels: FUN Team

#1994 🔧(back) configure saml_fer settings wantNameId and allowRepeatAttributeName
  CHANGELOG.md
  src/backend/marsha/settings.py
Labels: improvement
