Repository openfun/marsha, pull requests merged in 2023-06, with the labels that each got.

#2283 🔧(back) filter dockerflow healthcheck in sentry before_send_transaction
  CHANGELOG.md
  src/backend/marsha/core/sentry.py
  src/backend/marsha/core/tests/test_sentry.py
  src/backend/marsha/settings.py
Labels: improvement

#2285 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#2287 🔖(minor) bump release to 4.2.0
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
Labels: FUN Team

#2288 ✨(back) create a default playlist for new shibboleth user
  CHANGELOG.md
  src/backend/marsha/account/factories.py
  src/backend/marsha/account/social_pipeline/__init__.py
  src/backend/marsha/account/social_pipeline/playlist.py
  src/backend/marsha/account/tests/test_social_pipeline_playlist.py
Labels: feature request

#2295 📄(front) change lib-video license to MIT
  src/frontend/packages/lib_video/package.json
Labels: FUN Team

#2292 ⬆️(back) upgrade to django 4.2
  CHANGELOG.md
  UPGRADE.md
  docs/env.md
  renovate.json
  src/backend/marsha/core/tests/test_statics.py
  src/backend/marsha/settings.py
  src/backend/setup.cfg
Labels: improvement, FUN Team

#2300 🐛(frontend) video player reset
  CHANGELOG.md
  src/frontend/packages/lib_video/src/components/common/VideoPlayer/index.tsx
  src/frontend/packages/lib_video/src/hooks/useSetVideoState/index.tsx
Labels: bug, easy pick, Frontend
