Repository openfun/marsha, pull requests merged in 2023-02, with the labels that each got.

#2003 :bug:(backend) change xapi endpoints status code
  CHANGELOG.md
  CONTRIBUTORS.md
  src/backend/marsha/core/api/xapi.py
  src/backend/marsha/core/tests/test_api_xapi_statement.py
Labels: improvement

#1984 🏗️(tray) bootstrap arnold tray
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  arnold.yml
  src/tray/templates/services/app/_deploy_base.yml.j2
  src/tray/templates/services/app/_env.yml.j2
  src/tray/templates/services/app/configs/__init__.py.j2
  src/tray/templates/services/app/configs/settings.py.j2
  src/tray/templates/services/app/cronjob_check_harvested.yml.j2
  src/tray/templates/services/app/cronjob_check_live_state.yml.j2
  src/tray/templates/services/app/cronjob_clean_aws_elemental_stack.yml.j2
  src/tray/templates/services/app/cronjob_clean_medialive_dev_stack.yml.j2
  src/tray/templates/services/app/cronjob_clean_mediapackages.yml.j2
  src/tray/templates/services/app/cronjob_prefetch_saml_fer_metadata.yml.j2
  src/tray/templates/services/app/deploy_app.yml.j2
  src/tray/templates/services/app/deploy_xapi.yml.j2
  src/tray/templates/services/app/job_db_migrate.yml.j2
  src/tray/templates/services/app/secret.yml.j2
  src/tray/templates/services/app/secret_cloudfront_private_key.yml.j2
  src/tray/templates/services/app/svc_app.yml.j2
  src/tray/templates/services/app/svc_xapi.yml.j2
  src/tray/templates/services/nginx/configs/healthcheck.conf.j2
  src/tray/templates/services/nginx/configs/marsha.conf.j2
  src/tray/templates/services/nginx/deploy.yml.j2
  src/tray/templates/services/nginx/ingress.yml.j2
  src/tray/templates/services/nginx/secret.yml.j2
  src/tray/templates/services/nginx/static-svc.yml.j2
  src/tray/templates/services/nginx/svc.yml.j2
  src/tray/templates/services/postgresql/deploy.yml.j2
  src/tray/templates/services/postgresql/ep.yml.j2
  src/tray/templates/services/postgresql/secret.yml.j2
  src/tray/templates/services/postgresql/svc.yml.j2
  src/tray/templates/volumes/media.yml.j2
  src/tray/templates/volumes/static.yml.j2
  src/tray/tray.yml
  src/tray/vars/all/main.yml
  src/tray/vars/settings.yml
  src/tray/vars/vault/main.yml.j2
Labels: improvement, feature

#2015 ➕(brack) install scoutapm package
  CHANGELOG.md
  src/backend/marsha/settings.py
  src/backend/setup.cfg
Labels: improvement, Backend

#2016 🐛(front) fix duplicated intl message id in HomeBanner
  src/frontend/apps/standalone_site/src/features/HomePage/components/HomePage.tsx
Labels: bug

#2017 🔧(tray) set limit to marsha pod resources
  src/tray/vars/all/main.yml
Labels: improvement

#2018 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#2023 ♻️(tray) create a cronjob pipeline
  CHANGELOG.md
  src/tray/templates/services/app/cronjob_check_harvested.yml.j2
  src/tray/templates/services/app/cronjob_check_live_state.yml.j2
  src/tray/templates/services/app/cronjob_clean_aws_elemental_stack.yml.j2
  src/tray/templates/services/app/cronjob_clean_medialive_dev_stack.yml.j2
  src/tray/templates/services/app/cronjob_clean_mediapackages.yml.j2
  src/tray/templates/services/app/cronjob_pipeline.yml.j2
  src/tray/templates/services/app/cronjob_prefetch_saml_fer_metadata.yml.j2
  src/tray/vars/all/main.yml
Labels: improvement

#2030 💄(lti) position modal above tooltip
  CHANGELOG.md
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/FoldableItem/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/FoldableItem/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/WidgetsContainer/InfoModal/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/WidgetsContainer/InfoModal/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/WidgetsContainer/index.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DownloadVideo/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadClosedCaptions/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadSubtitles/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadTranscripts/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadVideo/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/WidgetThumbnail/index.spec.tsx
  src/frontend/packages/lib_video/src/hooks/useInfoWidgetModal/index.ts
Labels: improvement

#2022 [Snyk] Security upgrade python from 3.10-bullseye to 3.10.9-slim
  CHANGELOG.md
  CONTRIBUTORS.md
  Dockerfile
Labels: improvement

#2027 ✨(backend) add user API endpoints
  CHANGELOG.md
  docs/permissions.md
  src/backend/marsha/core/api/account.py
  src/backend/marsha/core/permissions.py
  src/backend/marsha/core/serializers/account.py
  src/backend/marsha/core/tests/api/users/__init__.py
  src/backend/marsha/core/tests/api/users/test_list.py
  src/backend/marsha/core/tests/api/users/test_retrieve.py
  src/backend/marsha/core/tests/api/users/test_update.py
  src/backend/marsha/core/tests/api/users/test_whoami.py
Labels: Backend

#2035 🐛(LTI) bug on the textarea of the live video
  CHANGELOG.md
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SchedulingAndDescription/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SchedulingAndDescription/index.tsx
Labels: bug

#2047 ♻️(back) allow public resource to be embedded in a iframe
  CHANGELOG.md
  src/backend/marsha/core/tests/test_views_public_document.py
  src/backend/marsha/core/tests/test_views_public_video.py
  src/backend/marsha/core/views.py
Labels: improvement

#2011 📝(sprint) add sprint review #6 from 2023-01-27
  docs/sprint-reviews/2023-01-27-sprint-review#6.md
Labels: FUN Team

#2053 🐛(back) manage header cache on public resources view
  src/backend/marsha/core/tests/test_views_public_document.py
  src/backend/marsha/core/tests/test_views_public_video.py
  src/backend/marsha/core/views.py
  src/backend/marsha/settings.py
Labels: bug

#2055 🐛(back) change schema url_name used by swagger view
  src/backend/marsha/development/urls.py
Labels: bug

#2059 ♻️(front) change DashboardTabStatistics label to display viewers
  src/frontend/packages/lib_video/src/components/common/DashboardControlPane/DashboardTabStatistics/index.spec.tsx
  src/frontend/packages/lib_video/src/components/common/DashboardControlPane/DashboardTabStatistics/index.tsx
  src/frontend/packages/lib_video/src/components/common/DashboardControlPane/index.tsx
Labels: improvement

#2065 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/lti_site/i18n/es_ES.json
  src/frontend/apps/lti_site/i18n/fr_CA.json
  src/frontend/apps/lti_site/i18n/fr_FR.json
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#2068 🔖(beta) bump release to 4.0.0-beta.16
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/tray/tray.yml
Labels: FUN Team

#2078 Feature/qbey/timed text track permissions
  CHANGELOG.md
  src/backend/marsha/core/api/timed_text_track.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_create.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_delete.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_initiate_upload.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_list.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_retrieve.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_update.py
Labels: Backend

#2084 Chat sync bug fix
  CHANGELOG.md
  src/frontend/packages/lib_video/src/components/live/common/Chat/ChatConversationDisplayer/index.spec.tsx
  src/frontend/packages/lib_video/src/components/live/common/Chat/ChatMessageGroupItem/index.tsx
Labels: bug

#2081 🚨(tray) avoid using punctuation with password lookup
  src/tray/vars/vault/main.yml.j2
Labels: improvement

#2085 🐛(backend) allow timed text tracks OPTIONS
  src/backend/marsha/core/api/timed_text_track.py
  src/backend/marsha/core/tests/api/timed_text_tracks/test_options.py
Labels: Backend
