Repository openfun/marsha, pull requests merged in 2024-10, with the labels that each got.

#2630 ♻️(tray) split websocket and asgi apps in tray
  CHANGELOG.md
  src/tray/templates/services/app/deploy_ws.yml.j2
  src/tray/templates/services/app/svc_ws.yml.j2
  src/tray/templates/services/nginx/configs/marsha.conf.j2
  src/tray/vars/all/main.yml
Labels: improvement

#2632 ♻️(peertube) use new peertube runner docker image syntax
  env.d/peertube_runner
  src/backend/marsha/development/management/commands/load_development_datasets.py
Labels: FUN Team

#2627 ✨(front) display founders logo in the Footer
  src/frontend/apps/standalone_site/src/assets/img/europe.png
  src/frontend/apps/standalone_site/src/assets/img/france-relance.png
  src/frontend/apps/standalone_site/src/assets/img/ministere.svg
  src/frontend/apps/standalone_site/src/features/Footer/components/Footer.spec.tsx
  src/frontend/apps/standalone_site/src/features/Footer/components/Footer.tsx
Labels: improvement

#2633 ⚗️(front) remove websocket connection in VOD student dashboard
  CHANGELOG.md
  src/frontend/packages/lib_video/src/components/vod/Student/Dashboard.tsx
Labels: improvement

#2636 🌐(i18n) update french translations
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/apps/standalone_site/i18n/es_ES.json
  src/frontend/apps/standalone_site/i18n/fr_CA.json
  src/frontend/apps/standalone_site/i18n/fr_FR.json
  src/frontend/packages/i18n/es_ES.json
  src/frontend/packages/i18n/fr_CA.json
  src/frontend/packages/i18n/fr_FR.json
Labels: FUN Team

#2637 🐛(back) use right settings module in s3 task
  src/backend/marsha/core/tasks/s3.py
Labels: bug

#2638 🔖(minor) bump release to 5.1.0
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
  src/webtorrent/package.json
Labels: FUN Team

#2649 ♻️(back) allow all users created via shibboleth to have a playlist
  CHANGELOG.md
  src/backend/marsha/account/social_pipeline/playlist.py
  src/backend/marsha/account/tests/test_social_pipeline_playlist.py
  src/backend/marsha/core/defaults.py
Labels: feature request, Backend

#2650 🔖(minor) bump release to 5.2.0
  CHANGELOG.md
  arnold.yml
  src/aws/lambda-complete/package.json
  src/aws/lambda-configure/package.json
  src/aws/lambda-convert/package.json
  src/aws/lambda-elemental-routing/package.json
  src/aws/lambda-medialive/package.json
  src/aws/lambda-mediapackage/package.json
  src/aws/lambda-migrate/package.json
  src/aws/utils/update-state/package.json
  src/backend/setup.cfg
  src/frontend/apps/lti_site/package.json
  src/frontend/apps/standalone_site/package.json
  src/frontend/package.json
  src/frontend/packages/eslint-config-marsha/package.json
  src/frontend/packages/lib_classroom/package.json
  src/frontend/packages/lib_common/package.json
  src/frontend/packages/lib_components/package.json
  src/frontend/packages/lib_markdown/package.json
  src/frontend/packages/lib_tests/package.json
  src/frontend/packages/lib_video/package.json
  src/frontend/packages/marsha-config/package.json
  src/tray/tray.yml
  src/webtorrent/package.json
Labels: FUN Team

#2653 🐛(front) enable join classroom button with local storage username
  CHANGELOG.md
  src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.spec.tsx
  src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.tsx
Labels: bug

#2654 🔧(tray) connect runner to ws pods
  CHANGELOG.md
  src/tray/templates/services/nginx/configs/marsha.conf.j2
Labels: improvement
